const sharp=require('sharp'); const fs=require('fs');
const out=process.cwd();
const scenes=[
['new-customer-trust','Maya | AutoLink',['Before I send anything, I need to know I’m dealing with a real exporter.','That’s completely fair. I’ll send our business license, warehouse video, and the VIN report.','Can you put today’s date next to the car in the video?','Yes. You can verify every detail before making a decision.','I appreciate that. I feel comfortable moving forward with the inspection.']],
['long-term-cooperation','Daniel | Westline Motors',['The last four shipments arrived exactly as promised.','For the fifth shipment, I’ve reserved the same inspection team and shipping route.','That’s why I keep coming back. No surprises, no chasing for updates.','I’ll send SUV options that match your market and budget.','Perfect. Please prepare the proforma invoice.']],
['urgent-delivery','Omar | Prime Auto Hub',['The vessel cutoff is tonight. If we miss it, my customer will cancel.','I understand. I’m checking the port status now.','Can the export documents be corrected today?','Good news — documents approved. Pickup is confirmed for 7:30 PM.','You saved this shipment. Thank you for acting so quickly.']],
['high-satisfaction-repeat-order','Sofia | DrivePoint',['The three cars arrived yesterday, and they’re even better than the photos.','That’s wonderful to hear. How did your customers react?','They loved the condition. I sold two within the week.','Can you reserve five more vehicles, including two hybrids?','Absolutely. I’ll send the best matches this afternoon.']]
];
function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/'/g,'&apos;')}
function wrap(s,n=48){let a=[]; while(s.length>n){let i=s.lastIndexOf(' ',n); if(i<1)i=n;a.push(s.slice(0,i));s=s.slice(i+1)}a.push(s);return a}
function bubble(text,x,y,w,right,idx){let lines=wrap(text,Math.floor(w/14));let h=lines.length*26+28;let xx=right?x+w: x; let rect=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="${right?'#d9fdd3':'#fff'}"/>`; let t=lines.map((l,i)=>`<text x="${x+16}" y="${y+26+i*26}" class="msg">${esc(l)}</text>`).join(''); let meta=`<text x="${x+w-70}" y="${y+h-9}" class="time">${['10:42','10:43','10:44','10:45','10:47'][idx]} ${right?'✓✓':''}</text>`; return rect+t+meta}
function make(name,contact,msgs){let y=150, body=''; msgs.forEach((m,i)=>{let right=i%2===1,w=Math.min(760,Math.max(370,m.length*10+70));let x=right?1200-w-45:45;body+=bubble(m,x,y,w,right,i);y+=95+(m.length>70?20:0)});return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800"><defs><pattern id="p" width="120" height="120" patternUnits="userSpaceOnUse"><rect width="120" height="120" fill="#efe9df"/><g fill="none" stroke="#e4dcd1" stroke-width="3" opacity=".65"><circle cx="22" cy="26" r="14"/><path d="M70 18l8 18 20 2-15 13 5 20-18-10-18 10 5-20-15-13 20-2z"/><path d="M18 90q20-28 40 0t40 0"/></g></pattern></defs><rect width="1200" height="800" fill="url(#p)"/><rect width="1200" height="112" fill="#fff"/><circle cx="58" cy="56" r="38" fill="#c7c7c7"/><circle cx="58" cy="56" r="30" fill="#999"/><text x="115" y="65" class="name">${esc(contact)}</text><g stroke="#111" stroke-width="6" fill="none" stroke-linecap="round"><rect x="1000" y="39" width="34" height="28" rx="3"/><path d="M1034 46l18-10v40l-18-10M1090 38q25 0 25 25M1115 63l15 8M1155 42l30 30M1185 42l-30 30"/></g>${body}<rect x="32" y="742" width="1136" height="42" rx="21" fill="#fff"/><text x="58" y="769" class="hint">Type a message</text><style>.name{font:28px Arial;fill:#111}.msg{font:21px Arial;fill:#111}.time{font:16px Arial;fill:#667781}.hint{font:20px Arial;fill:#9aa0a4}</style></svg>`}
(async()=>{for(const [n,c,m] of scenes)await sharp(Buffer.from(make(n,c,m))).png().toFile(`${out}/${n}.png`)})()
